version: "3.9"

services:
  web:
    build: .
    command: gunicorn helloworld.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-!4r%s-j2fp@+#1t0-9%jwmgq(v8wy4m&*-j-h)9c&^_ws37wt!"
      - "DJANGO_DEBUG=True"
      - "POSTGRES_NAME=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
